### ISSUE TITLE
Getting error when running "make local-test-cdc" in module-2

### ISSUE THREAD

**Issue by thi3nnq** [decodingml/llm-twin-course#15]
<img width="1412" alt="Screenshot 2024-05-06 at 06 38 59" src="https://github.com/decodingml/llm-twin-course/assets/55661060/88cf3630-cb8c-4fc7-95f3-759fa78add71">
I'm using mac M1 (macOS Sonoma), I run "make local-start". After that, when I run "make local-test-cdc" I got: " An error occurred: mongo1:30001: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),mongo3:30003: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),mongo2:30002: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 663816ca7f44e1af8ecad8fe, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('mongo1', 30001) server_type: Unknown, rtt: None, error=AutoReconnect('mongo1:30001: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo2', 30002) server_type: Unknown, rtt: None, error=AutoReconnect('mongo2:30002: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('mongo3', 30003) server_type: Unknown, rtt: None, error=AutoReconnect('mongo3:30003: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>".

Can anyone help me fix this error?

**Comment by alexandruvesa** [comment]
Hello @thi3nnq  !
You must do this 

Host Configuration

To ensure that your Docker containers can communicate with each other you need to update your /etc/hosts file. Add the following entries to map the hostnames to your local machine:

# Docker MongoDB Hosts Configuration
127.0.0.1       mongo1
127.0.0.1       mongo2
127.0.0.1       mongo3

we will update today the README and include these settings
