### ISSUE TITLE
Where should I start with this code at the Course1

### ISSUE THREAD

**Issue by RemixaWorld** [decodingml/llm-twin-course#25]
Thank you for your selfless sharing!
I hope this message finds you well. I am new to this project and very excited about contributing to it. I have gone through the readme but find myself a bit lost on, where to begin with running course1.

I apologize if this information is available and I missed it.  I am eager to learn and any guidance you can provide would be greatly appreciated.

**Comment by mukeshbhandarkar** [comment]
Hey,
@Remixa-python First you have to study lesson 1 then come to the repository and check the course folder from there you can start your coding practice.

**Comment by iusztinpaul** [comment]
Hello,

The easier way is to follow the articles, but I also added an INSTALL_AND_USAGE.md doc to make things easier to run.
