### ISSUE TITLE
Source code and Tutorial is not aligned

### ISSUE THREAD

**Issue by air71818** [decodingml/llm-twin-course#30]
Hi, when I learning in this [course](https://medium.com/decodingml/the-role-of-feature-stores-in-fine-tuning-llms-22bd60afd4b9), found that 

>In [insert_data_mongo.py](https://github.com/decodingml/llm-twin-course/blob/main/course/module-3/insert_data_mongo.py) we already prepare articles and posts, crawled from our platforms.

in `2. Insert Data into MongoDB`, the [insert_data_mongo.py](https://github.com/decodingml/llm-twin-course/blob/main/course/module-3/insert_data_mongo.py) is not exist, could you please update it latest version?
Thanks.

**Comment by iusztinpaul** [comment]
Hello,

We just updated the articles and links. We refactored the code to make it easier to run.

Just follow the instructions under `INSTALL_AND_USAGE` and you should be good to go.
