### ISSUE TITLE
let's Collaborate

### ISSUE THREAD

**Issue by HealthInnovators** [decodingml/llm-twin-course#31]
We have been following your tutorial, amazing work! The instructions and the code are not aligned can you please help? 

We are working on this, would you like to collaborate with us - https://www.aiforall.buzz/

**Comment by air71818** [comment]
Hi @HealthInnovators, currently I do some research on this repo, could we collaborate on this part? do some study or research and share about what we found.

**Comment by iusztinpaul** [comment]
Hello,

I just updated the articles with the latest link. We had to refactor the repo to simplify it, and the links got broken.
