### ISSUE TITLE
Unable to test data crawling locally

### ISSUE THREAD

**Issue by saikumaraili** [decodingml/llm-twin-course#33]
Hi,
Thank you for creating this course. This is awesome. With the updated instructions on [INSTALL_AND_USAGE.md](https://github.com/decodingml/llm-twin-course/blob/main/INSTALL_AND_USAGE.md) file, I am able to spin up the infrastructure on my Mac M1.

But when I run `make local-test-github` command. I am getting an error with status 500. Here is the snapshot of the error.

<img width="955" alt="Screenshot 2024-08-01 at 5 39 02 PM" src="https://github.com/user-attachments/assets/88eba6d3-3956-40b1-98f6-308147b30247">

Could you please let me guide me here?

Thanks

Sai

**Comment by iusztinpaul** [comment]
Hello, 

I am excited that you enjoy it!

Please make sure that you have added the latest changes to the repository. To do so:

1. Delete all the Docker containers
2. Pull the latest changes: `git pull`
3. Run everything again

If this error still persists, please let me know.

**Comment by saikumaraili** [comment]
Thank you for updating the repository. The issue is resolved. 👍🏻
