### ISSUE TITLE
Running Individual Components 

### ISSUE THREAD

**Issue by RishiRavula** [decodingml/llm-twin-course#36]
Since we are employing a microservice architecture. Is it possible to run each docker fully contained in its own ecosystem so we can see it function on its own without dependencies on other components 

(i.e. i JUST want to see the data/web crawler run on its own without anything else so i can analyze how it works)

Would be great as we progress through the medium articles!

**Comment by iusztinpaul** [comment]
Hello @RishiRavula ,

Yes, you can do that.

Let me know if you have any other questions.
