### ISSUE TITLE
Missing Dockerfile in ./course/module-1

### ISSUE THREAD

**Issue by HalberdOfPineapple** [decodingml/llm-twin-course#38]
I tried to build this project from scratch incrementally but found the Github Action will fail in the job `build` because the `Dockerfile` is missing in `./course/module-1`:
```
buildx failed with: ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
```

I am wondering whether this is your mistake, or should I create a Dockerfile by myself based on `docker-compose.yml`?
Sorry I am just a fresher in CI/CD and this may sound like a naive question.

**Comment by iusztinpaul** [comment]
Hello, 

The GitHub Actions files need to be updated, but you spotted the issue right, we did some refactorings and moved the Dockerfiles under `.docker`
