### ISSUE TITLE
running crawler on AWS Lambda

### ISSUE THREAD

**Issue by Nic-J** [decodingml/llm-twin-course#41]
Hello,

Thanks a lot for the nice course. I'm following along and trying to make everything work. I can't get the AWS Lambda to work (it's timing out). I guess that's because I haven't figured out how to connect it with MongoDB. Everything works locally with Docker Compose since MongoDB has 3 separate containers, ports are mapped to crawler etc, but from what I can see, deploying the crawler to AWS only creates the crawler container, so there's not MongoDB to talk to. It would be good to have more details on how to make this part of the pipeline run on the cloud as well.

**Comment by iusztinpaul** [comment]
Hello,

Unfortunately, we don't support full AWS deployment anymore.
